### ISSUE TITLE
Update Link to Common Syllabus

### ISSUE THREAD

**Issue by code-warrior** [code-warrior/CSCI-UA.0004-003#2]

**Comment by code-warrior** [comment]
@jclayton : What is the link to spring 2019’s common syllabus? I’m using [`https://cs.nyu.edu/courses/spring19/CSCI-UA.0004-001/common-syllabus/`](https://cs.nyu.edu/courses/spring19/CSCI-UA.0004-001/common-syllabus/), but that appears to be incorrect.

**Comment by jclayton** [comment]
@code-warrior here you go: [https://cs.nyu.edu/courses/spring19/CSCI-UA.0380-001/common-syllabus/](https://cs.nyu.edu/courses/spring19/CSCI-UA.0380-001/common-syllabus/) 🏄

**Comment by code-warrior** [comment]
Resolved with merge commit `d77e8a4a129955b255b0db462e3f87d6d3b1c421`

**Comment by code-warrior** [comment]
Many thanks, @jclayton.
